
export enum StoryPreferences {
  ADVENTURE = 'Adventure',
  EDUCATIONAL = 'Educational',
  FANTASY = 'Fantasy',
  SCIFI = 'Sci-Fi',
  MYSTERY = 'Mystery',
  FUNNY = 'Funny',
}

export enum StoryLength {
  SHORT = 'Short (3-4 Scenes)',
  MEDIUM = 'Medium (5-7 Scenes)',
  LONG = 'Long (8-10 Scenes)',
}

export enum Gender {
  NONE = 'Prefer not to specify',
  MALE = 'Male',
  FEMALE = 'Female',
  NON_BINARY = 'Non-binary',
}

export enum TtsProvider {
  ELEVENLABS = 'ElevenLabs',
  BROWSER = 'Browser',
}

export interface LanguageOption {
  code: string; // BCP 47 language code e.g., 'en-US', 'tr-TR'
  name: string; // Display name e.g., 'English', 'Turkish'
}

export interface PersonalizedCharacter {
  id: string; // For React keys
  name: string;
  imagePreviewUrl: string; // For UI display
  base64Data: string; // For API call
  mimeType: string;
  isProcessing: boolean; // To show a spinner on the character card
  description: string | null; // Generated by AI
}

export interface StoryConfig {
  theme: string;
  age: number;
  gender: Gender;
  preference: StoryPreferences;
  length: StoryLength;
  elementsToInclude: string;
  characterNames: string;
  language: string; // Language code, e.g., 'en-US'
  personalizedCharacters: PersonalizedCharacter[];
  ttsProvider: TtsProvider;
}

export interface Scene {
  scene_text: string;
  illustration_prompt: string;
  imageUrl?: string;
  audioUrl?: string; // URL for the generated audio blob for this scene
  audioBase64?: string; // Base64 encoded audio data for embedding
  isGeneratingAudio?: boolean; // Flag to indicate audio is being generated for this scene
}

export interface CharacterDescription {
  name: string;
  description: string;
}

export interface StoryData {
  title: string;
  scenes: Scene[];
  language: string; // Language code, e.g., 'en-US', 'tr-TR'
  ttsProvider: TtsProvider;
  character_descriptions?: CharacterDescription[];
  isExporting?: boolean; // Flag for audiobook export process
  exportProgress?: string; // Progress message for the export
}
